version: "2"
services:
  db:
    image: postgres:11.1-alpine
    restart: always
    env_file:
    - .env
    volumes:
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d/

  prosodyfiler:
    build: ./prosody-filer/
    restart: always

  reverseproxy:
    image: nginx:1.15.8-alpine
    volumes:
      - ./conf.d/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./conf.d/nginx/uploads.xmpp.ga.conf:/etc/nginx/conf.d/uploads.xmpp.ga.conf:ro
      - ./certs/proxy:/etc/certs/:ro
    restart: always
    depends_on:
      - prosodyfiler

  prosody:
    build:
      context: ./prosody/
      args:
        PREFIX: /opt/prosody-0.11.1
    restart: always
    environment:
      PROSODY_POSTGRES_PASSWORD: prosody
    volumes:
      - ./conf.d/prosody/prosody.cfg.lua:/opt/prosody-0.11.1/etc/prosody/prosody.cfg.lua:ro
      - ./conf.d/prosody/mail.solay.ga.cfg.lua:/opt/prosody-0.11.1/etc/prosody/conf.d/mail.solay.ga.cfg.lua:ro
      - ./certs/prosody:/opt/prosody-0.11.1/etc/prosody/certs
    ports:
      - 5000:5000
      - 5222:5222
      - 5223:5223
      - 5269:5269
      - 5280:5280
      - 5281:5281
    depends_on:
      - reverseproxy
      - db
