#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    CREATE USER $PROSODY_POSTGRES_USER WITH PASSWORD '$PROSODY_POSTGRES_PASSWORD';
    CREATE DATABASE $PROSODY_POSTGRES_DATABASE;
    GRANT ALL PRIVILEGES ON DATABASE $PROSODY_POSTGRES_DATABASE TO $PROSODY_POSTGRES_USER;
EOSQL